Reverting the commits
Reverting 363fc9c3f53c86553417163bcadddb95a655ed09
Reverting 0159d7723fa3ad9d649107668add84d94a252eea

diff --git a/testers/smlite_utils b/testers/smlite_utils
--- a/testers/smlite_utils
+++ b/testers/smlite_utils
@@ -584,9 +584,12 @@ function run_smgr_task() {
         echo "SM_SERVER_IP is not set, unable to proceede, aborting the process"
         exit 1
     fi
-
+    if [ -z $CLUSTER_NAME ] && [ -z $SERVER_NAME ]; then
+        echo "CLUSTER_NAME/SERVER_NAME env is not set, aborting the process"
+        exit 1
+    fi
     create_testbed || die "Failed to create required testbed details"
-    reimage_setup || debug_and_die "Reimage failed!"
+    reimage_setup_using_SM || debug_and_die "Reimage failed!"
     JSON=`echo $TBFILE | sed 's/.py/.json/'`
     echo $JSON
     echo "JSON will be used to provision the setup."
diff --git a/testers/utils b/testers/utils
--- a/testers/utils
+++ b/testers/utils
@@ -879,10 +879,8 @@ function reimage_setup {
         # verify reimage is successful or failure
         fab check_reimage_state  || debug_and_die "Check to validate reimaging failed"
     fi
-    if [[ ( "$BRANCH" < "R4.0" ) && ( ${BRANCH} != "mainline" ) ]]; then
-        (cd ${TOOLS_WS}/contrail-fabric-utils;
-         fab set_allow_unsupported_sfp ) || echo "Unable to enable unsupported sfp"
-    fi
+    (cd ${TOOLS_WS}/contrail-fabric-utils;
+    fab set_allow_unsupported_sfp ) || echo "Unable to enable unsupported sfp"
 }
 
 ##
