changes for Vcenter-as-compute

diff --git a/testers/smlite_utils b/testers/smlite_utils
--- a/testers/smlite_utils
+++ b/testers/smlite_utils
@@ -119,11 +119,22 @@ function reimage_setup_using_SM {
         isofile="/root/images/centos71.json"
     fi
 
-    echo "Connect to SM_SERVER to reimage the targets"
+    echo "Cconnect to SM_SERVER to reimage the targets"
+
+    # check whether skip_reimage of servers set
+    reimage_flag=$(sshpass -p "c0ntrail123" ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -l root $SM_SERVER_IP '/usr/bin/server-manager-client display server --detail --json | grep -A2 tag | grep skip_reimage | grep -c true')
+
     sshpass -p "c0ntrail123" ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -l root $SM_SERVER_IP " (
         set -e
         echo "reimage the target setup"
-        server-manager-client reimage -F --cluster_id $CLUSTER_NAME ${image_id}
+        if [ $reimage_flag > 1 ]
+        then
+            echo "use tag to avoid reimaging servers which dont need it"
+            server-manager reimage -F --tag skip_reimage=false ${image_id}
+        else
+            server-manager-client reimage -F --cluster_id $CLUSTER_NAME ${image_id}
+        fi
+
         if [ $? == 0 ]
         then
             echo "Issue of Reimage command to reimage target nodes is sucessful!!!"
@@ -136,22 +147,30 @@ function reimage_setup_using_SM {
         sleep 10
 
         #check if reimage is completed.
-        /root/sm_files/check_reimage_cliff.sh $CLUSTER_NAME
+        if [ $reimage_flag > 1 ]
+        then
+            echo "check only those servers issued reimage based on tags"
+            /root/sm_files/check_reimage_tags_cliff.sh "skip_reimage=false"
+        else
+            /root/sm_files/check_reimage_cliff.sh $CLUSTER_NAME
+        fi
+
         if [ $? == 0 ]
         then
-            echo "reimaged the target $CLUSTER_NAME successfully"
+            echo "reimaged the target nodes successfully"
         else
-            echo "reimage of target $CLUSTER_NAME failed!!!"
+            echo "reimage of target nodes failed!!!"
             exit 1
         fi
 
     ) "
+
     if [ $? == 0 ]
     then
-        echo "reimaged the target $CLUSTER_NAME successfully"
+        echo "reimaged the target nodes successfully"
         sleep 150
     else
-        echo "reimage of target $CLUSTER_NAME failed!!!"
+        echo "reimage of target nodes failed!!!"
         exit 1
     fi
 
@@ -543,8 +562,8 @@ function run_smgr_task() {
 	set_json_file_path || die "setting json file path for cluster and server failed"
     fi
 
-    #if esxi/vcenter setup, cleanup vcenter and dockers
-    if [[ $VCENTER_ONLY_TESTBED -eq 1 ]]; then
+    # esxi/vcenter setup, cleanup vcenter and dockers
+    if [[ ( $VCENTER_ONLY_TESTBED -eq 1 ) || ( $VCENTER_AS_COMPUTE_TESTBED -eq 1 ) ]]; then
         (cd ${TOOLS_WS}/contrail-fabric-utils
          fab cleanup_vcenter)
         if [[ $SKIP_REIMAGE -eq 1 ]]; then
