Making changes for combines json in R4.0.

diff --git a/testers/smlite_utils b/testers/smlite_utils
--- a/testers/smlite_utils
+++ b/testers/smlite_utils
@@ -154,21 +154,16 @@ function reimage_setup_using_SM {
 function set_json_file_path {
     set -x
     folder_path=''
-    clusterjson=''
-    serverjson=''
+    json=''
 
     #For the time being we are not checking in the cluster and server json files in contrail-tools
     #folder_path=${TOOLS_WS}/testbeds
     #clusterjson=$folder_path/$CLUSTER_JSON
     #serverjson=$folder_path/$SERVER_JSON
     folder_path="/root/sm_files"
-    clusterjson=$folder_path/$CLUSTER_JSON
-    serverjson=$folder_path/$SERVER_JSON
+    json=$folder_path/$JSON
 
-    #[ -f $clusterjson ] || die "Cluster json file $clusterjson not found"
-    #[ -f $serverjson ] || die "Server json file $serverjson not found"
-    export ABS_PATH_CLUSTERJSON=$clusterjson
-    export ABS_PATH_SERVERJSON=$serverjson
+    export ABS_PATH_JSON=$json
 
 }
 
@@ -227,13 +222,21 @@ function copy_smlite_pkg() {
     echo $CONTRAIL_PACKAGE
     echo $SERVER_MANAGER_INSTALLER
     sleep 30
-    if [ -z $CLUSTER_JSON ] || [ -z $SERVER_JSON ]; then
+    if [ -z $JSON ]; then
         sshpass -p "c0ntrail123" scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r ${pkg_dir}/artifacts/${SERVER_MANAGER_INSTALLER} ${pkg_dir}/artifacts/${CONTRAIL_PACKAGE} $ABS_PATH_TBFILE ${API_SERVER_HOST_STRING}:/root/
 	exec_cmds -s root@$SM_SERVER_IP -p "c0ntrail123" -c "sshpass -p ${API_SERVER_HOST_PASSWORD} scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null /root/sm_files/check_provision_cliff.sh ${API_SERVER_HOST_STRING}:/root/"
     else
         sshpass -p "c0ntrail123" scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r ${pkg_dir}/artifacts/${SERVER_MANAGER_INSTALLER} ${pkg_dir}/artifacts/${CONTRAIL_PACKAGE} $ABS_PATH_TBFILE ${API_SERVER_HOST_STRING}:/root/
-	exec_cmds -s root@$SM_SERVER_IP -p "c0ntrail123" -c "sshpass -p ${API_SERVER_HOST_PASSWORD} scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null /root/sm_files/check_provision_cliff.sh $ABS_PATH_CLUSTERJSON $ABS_PATH_SERVERJSON ${API_SERVER_HOST_STRING}:/root/"
+	exec_cmds -s root@$SM_SERVER_IP -p "c0ntrail123" -c "sshpass -p ${API_SERVER_HOST_PASSWORD} scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null /root/sm_files/check_provision_cliff.sh $ABS_PATH_JSON ${API_SERVER_HOST_STRING}:/root/"
     fi
+    if [ $? == 0 ]
+    then
+        echo "Copy of ${SERVER_MANAGER_INSTALLER} and ${CONTRAIL_PACKAGE} to SMLITE server is successfull"
+    else
+        echo "Copy of ${SERVER_MANAGER_INSTALLER} and ${CONTRAIL_PACKAGE} to SMLITE server is failed!!!"
+        exit 1
+    fi
+
 }
 
 
@@ -281,7 +284,7 @@ function provision_using_SMLite() {
         set -x
         echo "Install SM-Lite and provision the target setup"
         dpkg -i /root/${SERVER_MANAGER_INSTALLER}
-        if [ -z $CLUSTER_JSON ] || [ -z $SERVER_JSON ]; then
+        if [ -z $JSON ]; then
             if [ $SKIP_SMLITE_INSTALL -ne 0 ]
             then
                 /opt/contrail/contrail_server_manager/provision_containers.sh -ni -c /root/${CONTRAIL_PACKAGE} -t /root/${tb_filename} -cid $CLUSTER_NAME
@@ -289,12 +292,12 @@ function provision_using_SMLite() {
                 /opt/contrail/contrail_server_manager/provision_containers.sh -c /root/${CONTRAIL_PACKAGE} -t /root/${tb_filename} -cid $CLUSTER_NAME
             fi
         else
-            echo '{\"image\":[{\"category\": \"package\", \"id\": \"$SMID\", \"type\": \"$pkg_type\", \"path\": \"$cntl_pkg\", \"version\":\"$BUILDID\"}]}' > /root/image.json
+            echo '\"image\":[{\"category\": \"package\", \"id\": \"$SMID\", \"type\": \"$pkg_type\", \"path\": \"$cntl_pkg\", \"version\":\"$BUILDID\"}]}' >> /root/${JSON}
             if [ $SKIP_SMLITE_INSTALL -ne 0 ]
             then
-                /opt/contrail/contrail_server_manager/provision_containers.sh -ni -ij /root/image.json -cj /root/${CLUSTER_JSON} -sj /root/${SERVER_JSON}
+                /opt/contrail/contrail_server_manager/provision_containers.sh -ni -j /root/${JSON}
             else
-                /opt/contrail/contrail_server_manager/provision_containers.sh -ij /root/image.json -cj /root/${CLUSTER_JSON} -sj /root/${SERVER_JSON}
+                /opt/contrail/contrail_server_manager/provision_containers.sh -j /root/${JSON}
             fi
         fi
 
@@ -383,11 +386,11 @@ function run_smgr_task() {
     fi
     create_testbed || die "Failed to create required testbed details"
     reimage_setup_using_SM || debug_and_die "reimage failed"
-    if [ -z $CLUSTER_JSON ] || [ -z $SERVER_JSON ]; then
-        echo "CLUSTER_JSON and SERVER_JSON env variables are not set."
+    if [ -z $JSON ]; then
+        echo "JSON env variables is not set."
 	echo "testbed.py will be used to provision the setup."
     else
-        echo "CLUSTER_JSON and SERVER_JSON will be used to provision the setup."
+        echo "JSON will be used to provision the setup."
 	set_json_file_path || die "setting json file path for cluster and server failed"
     fi
     copy_smlite_pkg || die "copy of sm-lite packages failed"
