disabling collect_tech_support, till problem is fixed and adding install_thirdpart_pkg routine

diff --git a/testers/smlite_utils b/testers/smlite_utils
--- a/testers/smlite_utils
+++ b/testers/smlite_utils
@@ -459,11 +459,11 @@ function run_smgr_task() {
     fi
     export TEST_HOST_IP=`echo $TEST_HOST_STRING | cut -d @ -f2`
     export TEST_HOST_USER=`echo $TEST_HOST_STRING | cut -d @ -f1`
-    #install_third_party_pkgs || die "installing GDB/ant failed"
+    install_third_party_pkgs || die "installing GDB/ant failed"
     setup_testnode || die "test node setup failed"
     install_dep_pkgs_for_test
     run_sanity_simple || die "run_sanity_simple failed"
     run_tempest || die "Run_Tempest step failed"
-    collect_tech_support || die "Task to collect logs/cores failed"
+    #collect_tech_support || die "Task to collect logs/cores failed"
     echo "Ending test on $1"
 }
