Standardizing json file name to be same as testbed file name.

diff --git a/testers/smlite_utils b/testers/smlite_utils
--- a/testers/smlite_utils
+++ b/testers/smlite_utils
@@ -591,13 +591,10 @@ function run_smgr_task() {
     fi
     create_testbed || die "Failed to create required testbed details"
     reimage_setup || debug_and_die "Reimage failed!"
-    if [ -z $JSON ]; then
-        echo "JSON env variables is not set."
-	echo "testbed.py will be used to provision the setup."
-    else
-        echo "JSON will be used to provision the setup."
-	set_json_file_path || die "setting json file path for cluster and server failed"
-    fi
+    JSON=`echo $TBFILE | sed 's/.py/.json/'`
+    echo $JSON
+    echo "JSON will be used to provision the setup."
+    set_json_file_path || die "setting json file path for cluster and server failed"
 
     # esxi/vcenter setup, cleanup vcenter and dockers
     if [[ ( $VCENTER_ONLY_TESTBED -eq 1 ) || ( $VCENTER_AS_COMPUTE_TESTBED -eq 1 ) ]]; then
