adding provision to skip provisioning and sanity run if 'SKIP_SANITY' parameter is not equal to 0

diff --git a/testers/utils_virtual b/testers/utils_virtual
--- a/testers/utils_virtual
+++ b/testers/utils_virtual
@@ -728,15 +728,19 @@ function add_server_cluster_SM() {
                 echo "Adding server to server-manager failed, aborting the process"
                 exit 1
             fi
-            echo "Preconfigure the servers"
-            python /opt/contrail/server_manager/client/preconfig.py --server-json $server_json  --server-manager-ip $SM_SERVER_IP --server-manager-repo-port 80    
-            if [ $? == 0 ]
+            if [ $SKIP_SANITY -e 0 ]
             then
-                echo "Preconfigure server through server-manager is sucessful!!!"
+                echo "Preconfigure the servers"
+                python /opt/contrail/server_manager/client/preconfig.py --server-json $server_json  --server-manager-ip $SM_SERVER_IP --server-manager-repo-port 80    
+                if [ $? == 0 ]
+                then
+                    echo "Preconfigure server through server-manager is sucessful!!!"
+                else
+                    echo "Preconfigure server through server-manager failed, aborting the process"
+                    exit 1
+                fi        
             else
-                echo "Preconfigure server through server-manager failed, aborting the process"
-                exit 1
-            fi            
+                echo "Not doing the Preconfig as 'SKIP_SANITY' parameter is not equal to 0 "    
         ) "
     fi
 
@@ -870,45 +874,51 @@ function run_smgr_virtual_task() {
     #Add server and cluster to the SM
     add_server_cluster_SM || debug_and_die "Failed to add server and cluster to SM"
 
-    if [[ ( ${BRANCH} > "R2.23" ) || ( ${BRANCH} == "mainline" ) ]]
-    then
-        provision_using_SM_cliff_client || debug_and_die "provision failed"
-    else
-        provision_using_SM || debug_and_die "provision failed"
-    fi
-    #check_kernel_upgrade || die "kernel upgrade failed"
-    export API_SERVER_HOST_STRING="root@"`cat ${TOOLS_WS}/config-node-ip`
-    
-    if [[ $TEST_RUN_INFRA == 'docker' ]]; then
-        search_package
-        pkg_file_name=`basename $PKG_FILE`
-        export PACKAGE_VERSION=`echo ${pkg_file_name} | sed 's/contrail-install-packages[-_]\([0-9\.\-]*\).*/\1/'`
-        if [[ -z $TEST_HOST_STRING ]]; then
-            export TEST_HOST_STRING=$API_SERVER_HOST_STRING
-            export TEST_HOST_PASSWORD=$API_SERVER_HOST_PASSWORD
-        fi
-        export TEST_HOST_IP=`echo $TEST_HOST_STRING | cut -d @ -f2`
-        export TEST_HOST_USER=`echo $TEST_HOST_STRING | cut -d @ -f1`
-        #Copy testbed_file generated by build_infra.sh
-        sshpass -p "c0ntrail123" scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@$BASE_CLUSTER:/root/${TEMPLATE_DIR}/testbed.py ${TOOLS_WS}/testbeds/${tb_filename}
-        setup_testnode || debug_and_die "test node setup failed"
-        install_dep_pkgs_for_test
-        run_sanity_simple || debug_and_die "run_sanity_simple failed"
-    else
-        add_sourcelist || die "source.list copy failed on all target nodes"
-        install_third_party_pkgs || die "installing GDB/ant failed"
-        install_dep_pkgs_for_test
-        run_sanity || debug_and_die "Run_sanity step failed"
-    fi
 
-    run_tempest || die "Run_Tempest step failed"
-    collect_tech_support || die "Task to collect logs/cores failed"
-    #delete_stacks || die "Failed to delete stacks"
-    echo "Ending test on "${AVAILABLE_TESTBEDS}
-    #Set the TBFILE_NAME to the one passed through jenkins job
-    export RUN_SUCCESSFUL=1
-    TBFILE_NAME=${AVAILABLE_TESTBEDS}
-    tb_lock_file=${LOCK_FILE_DIR}/${TBFILE_NAME}
+    if [ $SKIP_SANITY -e 0 ]
+    then
+        if [[ ( ${BRANCH} > "R2.23" ) || ( ${BRANCH} == "mainline" ) ]]
+        then
+            provision_using_SM_cliff_client || debug_and_die "provision failed"
+        else
+            provision_using_SM || debug_and_die "provision failed"
+        fi
+        #check_kernel_upgrade || die "kernel upgrade failed"
+        export API_SERVER_HOST_STRING="root@"`cat ${TOOLS_WS}/config-node-ip`
+        
+        if [[ $TEST_RUN_INFRA == 'docker' ]]; then
+            search_package
+            pkg_file_name=`basename $PKG_FILE`
+            export PACKAGE_VERSION=`echo ${pkg_file_name} | sed 's/contrail-install-packages[-_]\([0-9\.\-]*\).*/\1/'`
+            if [[ -z $TEST_HOST_STRING ]]; then
+                export TEST_HOST_STRING=$API_SERVER_HOST_STRING
+                export TEST_HOST_PASSWORD=$API_SERVER_HOST_PASSWORD
+            fi
+            export TEST_HOST_IP=`echo $TEST_HOST_STRING | cut -d @ -f2`
+            export TEST_HOST_USER=`echo $TEST_HOST_STRING | cut -d @ -f1`
+            #Copy testbed_file generated by build_infra.sh
+            sshpass -p "c0ntrail123" scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@$BASE_CLUSTER:/root/${TEMPLATE_DIR}/testbed.py ${TOOLS_WS}/testbeds/${tb_filename}
+            setup_testnode || debug_and_die "test node setup failed"
+            install_dep_pkgs_for_test
+            run_sanity_simple || debug_and_die "run_sanity_simple failed"
+        else
+            add_sourcelist || die "source.list copy failed on all target nodes"
+            install_third_party_pkgs || die "installing GDB/ant failed"
+            install_dep_pkgs_for_test
+            run_sanity || debug_and_die "Run_sanity step failed"
+        fi
+
+        run_tempest || die "Run_Tempest step failed"
+        collect_tech_support || die "Task to collect logs/cores failed"
+        #delete_stacks || die "Failed to delete stacks"
+        echo "Ending test on "${AVAILABLE_TESTBEDS}
+        #Set the TBFILE_NAME to the one passed through jenkins job
+        export RUN_SUCCESSFUL=1
+        TBFILE_NAME=${AVAILABLE_TESTBEDS}
+        tb_lock_file=${LOCK_FILE_DIR}/${TBFILE_NAME}
+    else
+        echo "Skipping Provisioning and Sanity Run as 'SKIP_SANITY' parameter is not equal to 0 "
+    fi
 }
 
 
