skip bringup from util

diff --git a/testers/utils b/testers/utils
--- a/testers/utils
+++ b/testers/utils
@@ -1380,7 +1380,9 @@ function run_task() {
     elif [ -z "$PROVISION_SM" ]
     then
        reimage_using_SM || debug_and_die "reimage failed"
-       bringup_setup || die "Bringup failed"
+       if ![ ${OSP10} == "OSP10" ]; then
+          bringup_setup || die "Bringup failed"
+       fi
     else
        reimage_using_SM || debug_and_die "reimage failed"
        provision_using_SM || debug_and_die "provision failed"
