commented checkout_fab_repo

diff --git a/testers/utils b/testers/utils
--- a/testers/utils
+++ b/testers/utils
@@ -1270,7 +1270,7 @@ function create_testbed {
 
     if [[ $TEST_RUN_INFRA == 'docker' ]]; then
         # No need to fetch test repos in case of docker
-        checkout_fab_repo || die "Unable to checkout fab/test repos" # No need to checkout test repo for container
+      #  checkout_fab_repo || die "Unable to checkout fab/test repos" # No need to checkout test repo for container
     else
         checkout_repo
     fi
