Porting changes from virtual_test branch to R3.2

diff --git a/testers/utils_virtual b/testers/utils_virtual
--- a/testers/utils_virtual
+++ b/testers/utils_virtual
@@ -1,4 +1,4 @@
-!/usr/bin/env bash
+#!/usr/bin/env bash
 #!/usr/bin/awk -f
 TOOLS_WS=${TOOLS_WS:-$(pwd)}
 multi_node=0
@@ -77,7 +77,19 @@ function check_SM_pkg_availability() {
     count=0
     if [ $SM_TYPE -eq 1 ] 
     then
-        pkg_dir="/cs-shared/github-build/${BRANCH}/${BUILDID}/ubuntu-14-04/${SKU}/artifacts"
+	if [[ $CB_SANITY -eq 1 ]]; then
+		if [[ $DISTRO =~ ubuntu-16 ]]; then
+			if [[ $TESTBED_LOCATION_US -eq 1 ]];then
+				pkg_dir="/cs-build/CB-${BRANCH}-ubuntu16-${SKU}/builds/${BUILDID}/archive/packages"
+			fi
+		else
+			if [[ $TESTBED_LOCATION_US -eq 1 ]];then
+				pkg_dir="/cs-build/CB-${BRANCH}-ubuntu14-${SKU}/builds/${BUILDID}/archive/packages"
+			fi
+		fi
+	else
+        	pkg_dir="/cs-shared/github-build/${BRANCH}/${BUILDID}/ubuntu-14-04/${SKU}/artifacts"
+	fi
     else
         pkg_dir="/cs-shared/github-build/${BRANCH}/${BUILDID}/centos64_os/${SKU}/artifacts"
     fi
@@ -85,8 +97,13 @@ function check_SM_pkg_availability() {
     while [ "$count" -ne 36 ]; do
         if ls $pkg_dir/contrail-server-manager-installer*
         then
-            echo "SM pkgs are present in artifacts"
-            break
+	    if [[ $CB_SANITY -eq 1 ]]; then
+	        echo "SM pkgs are present in /archive/packages"
+		break
+	    else
+                echo "SM pkgs are present in artifacts"
+                break
+	    fi
         else
             if [ "$count" -eq 35 ]
             then
@@ -597,8 +614,13 @@ function add_server_cluster_SM() {
         if [[ ( ${BRANCH} > "R3.2.99" ) || ( ${BRANCH} == "mainline" ) ]]
         then
             SMID="combined_image_mainline"
-            contrail_pkg=`ls /cs-shared/github-build/${BRANCH}/${BUILDID}/${DISTRO}/${SKU}/artifacts/contrail-cloud-docker*.tgz`
-            contrail_pkg_name=`ls contrail-cloud-docker*.tgz`
+	    if [[ $TESTBED_LOCATION_US -eq 1 ]];then
+	        contrail_pkg=`ls /cs-build/CB-${BRANCH}-ubuntu14-${SKU}/builds/${BUILDID}/archive/packages/contrail-cloud-docker*.tgz`
+		contrail_pkg_name=`ls contrail-cloud-docker*.tgz`
+	    else
+                contrail_pkg=`ls /cs-shared/github-build/${BRANCH}/${BUILDID}/${DISTRO}/${SKU}/artifacts/contrail-cloud-docker*.tgz`
+                contrail_pkg_name=`ls contrail-cloud-docker*.tgz`
+	    fi
         fi
 
         echo ${contrail_pkg}
@@ -634,32 +656,29 @@ function add_server_cluster_SM() {
             cd /root/sm_files 
 
             set -e
+            echo "add required image/server/cluster for reimage and provision of the target"
 
+            echo "delete iso image if it exists"
+            server-manager-client delete image --image_id ${iso_name}
 
-            if [ ${SKIP_ADD_ISO} == 0 ]
+            echo "add base ISO image to server manager database"
+            #echo "add base ISO image to server manager database"
+            server-manager-client upload-image --id ${iso_name} --version ${BUILDID} --category image --type ${iso_type} --file_name ${isofile}
+            if [ $? == 0 ]
             then
-                echo "delete iso image if it exists"
-                server-manager-client delete image --image_id ${iso_name}
-
-                echo "add base ISO image to server manager database"
-                server-manager-client upload-image --id ${iso_name} --version ${BUILDID} --category image --type ${iso_type} --file_name ${isofile}
-                if [ $? == 0 ]
-                then
-                    echo "Server-manager adding image command is successful"
-                else
-                    echo "Server-manager adding image command failed, aborting the process"
-                    exit 1
-                fi
-
-                echo "check if the image was added successfully"
-                server-manager-client display image --json | grep ${iso_name}
-                if [ $? != 0 ]
-                then
-                    echo "Adding Base ISO image failed"
-                    exit 1
-                fi
+                echo "Server-manager adding image command is successful"
+            else
+                echo "Server-manager adding image command failed, aborting the process"
+                exit 1
             fi
 
+            echo "check if the image was added successfully"
+            server-manager-client display image --json | grep ${iso_name}
+            if [ $? != 0 ]
+            then
+                echo "Adding Base ISO image failed"
+                exit 1
+            fi
 
             echo "delete contrail package if it exists"
             if [ ${BRANCH} == "R1.10" ]
@@ -679,7 +698,14 @@ function add_server_cluster_SM() {
                 server-manager upload_image $SMID ${BUILDID} $pkg_type $contrail_pkg_name
             fi
             sleep 120
-            echo "Server-manager adding contrail-package command is successful"
+	    /root/sm_files/check_image_add.sh $SMID
+	    if [ $? == 0 ]
+	    then
+                echo "Server-manager adding contrail-package command is successful"
+	    else
+	        echo "Server-manager adding contrail-package command failed!!! aborting the process"
+	        exit 1
+	    fi
     
             echo "Clean up cluster and server from SM database before adding."
             server-manager delete server --cluster_id $CLUSTER_NAME
@@ -833,57 +859,42 @@ function run_smgr_virtual_task() {
         echo "TEST_SETUP is not defined, abort the process"
         exit 1
     fi
+    if [ -z "$SM_SERVER_IP" ]
+    then
+        echo "SM_SERVER_IP is not set, unable to proceede, aborting the process"
+        exit 1
+    fi
 
     if [ -z $CLUSTER_NAME ]; then
         echo "CLUSTER_NAME env is not set, aborting the process"
         exit 1
     fi
     create_testbed || die "Failed to create required testbed details"
-    echo "------------------------------------"
-    export API_SERVER_HOST_STRING="root@"`cat ${TOOLS_WS}/config-node-ip`
-    #Copy testbed_file generated by build_infra.sh
-    sshpass -p "c0ntrail123" scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@$BASE_CLUSTER:/root/${TEMPLATE_DIR}/testbed.py ${TOOLS_WS}/testbeds/${tb_filename}
-    if [ $FAB_BRINGUP -eq 1 ] 
-    then
-        sshpass -p "c0ntrail123" ssh -l root -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $SM_SERVER_IP " (
-            mkdir /root/sm_files/
-            sudo apt-get install python-netaddr -y
-            sudo apt-get install python-paramiko -y
-        ) " 
-    
-        sshpass -p "c0ntrail123" scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@$BASE_CLUSTER:/root/${TEMPLATE_DIR}/*.json ${TOOLS_WS}/sm_files/ 
-        #Copy install and provision check shell scripts
-        sshpass -p "c0ntrail123" scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${TOOLS_WS}/sm_files/* root@$SM_SERVER_IP:/root/sm_files/
-        server_json="/root/sm_files/server.json"
-        #echo "SM_SERVER_IP is not set,  will use Fab to bringup cluster"
-        sshpass -p "c0ntrail123" ssh -l root -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $SM_SERVER_IP " (
-            python /root/sm_files/preconfig_fab.py --server-json $server_json  --server-manager-ip $SM_SERVER_IP --server-manager-repo-port 80    
-        ) " 
-        bringup_setup || die "Bringup failed"
-    else
-        bringup_SM_setup || debug_and_die "Failed to bringup SM setup"
-        #Add server and cluster to the SM
-        add_server_cluster_SM || debug_and_die "Failed to add server and cluster to SM"
-        if [[ ( ${BRANCH} > "R2.23" ) || ( ${BRANCH} == "mainline" ) ]]
-        then
-            provision_using_SM_cliff_client || debug_and_die "provision failed"
-        else
-            provision_using_SM || debug_and_die "provision failed"
-        fi
-    fi
+    bringup_SM_setup || debug_and_die "Failed to bringup SM setup"
+    #Add server and cluster to the SM
+    add_server_cluster_SM || debug_and_die "Failed to add server and cluster to SM"
 
+    if [[ ( ${BRANCH} > "R2.23" ) || ( ${BRANCH} == "mainline" ) ]]
+    then
+        provision_using_SM_cliff_client || debug_and_die "provision failed"
+    else
+        provision_using_SM || debug_and_die "provision failed"
+    fi
     #check_kernel_upgrade || die "kernel upgrade failed"
+    export API_SERVER_HOST_STRING="root@"`cat ${TOOLS_WS}/config-node-ip`
     
     if [[ $TEST_RUN_INFRA == 'docker' ]]; then
         search_package
         pkg_file_name=`basename $PKG_FILE`
-        export PACKAGE_VERSION=`echo ${pkg_file_name} | sed 's/contrail-install-packages[-_]\([0-9\.\-]*\).*/\1/'`
+        export PACKAGE_VERSION=`echo ${pkg_file_name} | sed 's/contrail-cloud-docker[-_]\([0-9\.\-]*\)-.*/\1/'`
         if [[ -z $TEST_HOST_STRING ]]; then
             export TEST_HOST_STRING=$API_SERVER_HOST_STRING
             export TEST_HOST_PASSWORD=$API_SERVER_HOST_PASSWORD
         fi
         export TEST_HOST_IP=`echo $TEST_HOST_STRING | cut -d @ -f2`
         export TEST_HOST_USER=`echo $TEST_HOST_STRING | cut -d @ -f1`
+        #Copy testbed_file generated by build_infra.sh
+        sshpass -p "c0ntrail123" scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@$BASE_CLUSTER:/root/${TEMPLATE_DIR}/testbed.py ${TOOLS_WS}/testbeds/${tb_filename}
         setup_testnode || debug_and_die "test node setup failed"
         install_dep_pkgs_for_test
         run_sanity_simple || debug_and_die "run_sanity_simple failed"
