update ARTIFACTS setting

diff --git a/testers/utils b/testers/utils
--- a/testers/utils
+++ b/testers/utils
@@ -208,7 +208,8 @@ function search_package {
     if [[ $CB_SANITY -eq 1 ]]; then
         export PKG_FILE_DIR=`dirname $PKG_FILE`
     else
-        ARTIFACTS_PKG=`dirname $PKG_FILE`
+        #ARTIFACTS_PKG=`dirname $PKG_FILE`
+        ARTIFACTS_PKG=`/github-build/${BRANCH}/${BUILDID}/${DISTRO}/${TEST_SKU}`
         export PKG_FILE_DIR=`dirname $ARTIFACTS_PKG`
     fi
 
@@ -397,8 +398,7 @@ function checkout_fab_repo {
     if [[ $CB_SANITY -eq 1 ]]; then
         sshpass -p $TASK_RUNNER_HOST_PASSWORD scp ${SSHOPT} $TASK_RUNNER_HOST_STRING:$PKG_FILE_DIR/contrail-fabric-utils*.tgz  . || die "Failed to copy fab artifacts to build host"
     else
-        #sshpass -p $TASK_RUNNER_HOST_PASSWORD scp ${SSHOPT} $TASK_RUNNER_HOST_STRING:$PKG_FILE_DIR/artifacts_extra/contrail-fabric-utils*.tgz  . || die "Failed to copy fab artifacts to build host"
-        sshpass -p $TASK_RUNNER_HOST_PASSWORD scp ${SSHOPT} $TASK_RUNNER_HOST_STRING:$TEST_CONTAINER_IMAGE_DIR/artifacts_extra/contrail-fabric-utils*.tgz  . || die "Failed to copy fab artifacts to build host"
+        sshpass -p $TASK_RUNNER_HOST_PASSWORD scp ${SSHOPT} $TASK_RUNNER_HOST_STRING:$PKG_FILE_DIR/artifacts_extra/contrail-fabric-utils*.tgz  . || die "Failed to copy fab artifacts to build host"
     fi
     tar xzf contrail-fabric-utils*.tgz
     rm -rf contrail-fabric-utils
