Fab based provisioning support

diff --git a/testers/utils_virtual b/testers/utils_virtual
--- a/testers/utils_virtual
+++ b/testers/utils_virtual
@@ -833,29 +833,32 @@ function run_smgr_virtual_task() {
         echo "TEST_SETUP is not defined, abort the process"
         exit 1
     fi
-    if [ -z "$SM_SERVER_IP" ]
-    then
-        echo "SM_SERVER_IP is not set, unable to proceede, aborting the process"
-        exit 1
-    fi
 
     if [ -z $CLUSTER_NAME ]; then
         echo "CLUSTER_NAME env is not set, aborting the process"
         exit 1
     fi
     create_testbed || die "Failed to create required testbed details"
-    bringup_SM_setup || debug_and_die "Failed to bringup SM setup"
-    #Add server and cluster to the SM
-    add_server_cluster_SM || debug_and_die "Failed to add server and cluster to SM"
-
-    if [[ ( ${BRANCH} > "R2.23" ) || ( ${BRANCH} == "mainline" ) ]]
-    then
-        provision_using_SM_cliff_client || debug_and_die "provision failed"
-    else
-        provision_using_SM || debug_and_die "provision failed"
-    fi
-    #check_kernel_upgrade || die "kernel upgrade failed"
     export API_SERVER_HOST_STRING="root@"`cat ${TOOLS_WS}/config-node-ip`
+    #Copy testbed_file generated by build_infra.sh
+    sshpass -p "c0ntrail123" scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@$BASE_CLUSTER:/root/${TEMPLATE_DIR}/testbed.py ${TOOLS_WS}/testbeds/${tb_filename}
+    if [[ ( -z "$SM_SERVER_IP" ) || ( ${FAB_BRINGUP} == 1) ]]
+    then
+        echo "SM_SERVER_IP is not set,  will use Fab to bringup cluster"
+        bringup_setup || die "Bringup failed"
+    else
+        bringup_SM_setup || debug_and_die "Failed to bringup SM setup"
+        #Add server and cluster to the SM
+        add_server_cluster_SM || debug_and_die "Failed to add server and cluster to SM"
+        if [[ ( ${BRANCH} > "R2.23" ) || ( ${BRANCH} == "mainline" ) ]]
+        then
+            provision_using_SM_cliff_client || debug_and_die "provision failed"
+        else
+            provision_using_SM || debug_and_die "provision failed"
+        fi
+    fi
+
+    #check_kernel_upgrade || die "kernel upgrade failed"
     
     if [[ $TEST_RUN_INFRA == 'docker' ]]; then
         search_package
@@ -867,8 +870,6 @@ function run_smgr_virtual_task() {
         fi
         export TEST_HOST_IP=`echo $TEST_HOST_STRING | cut -d @ -f2`
         export TEST_HOST_USER=`echo $TEST_HOST_STRING | cut -d @ -f1`
-        #Copy testbed_file generated by build_infra.sh
-        sshpass -p "c0ntrail123" scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@$BASE_CLUSTER:/root/${TEMPLATE_DIR}/testbed.py ${TOOLS_WS}/testbeds/${tb_filename}
         setup_testnode || debug_and_die "test node setup failed"
         install_dep_pkgs_for_test
         run_sanity_simple || debug_and_die "run_sanity_simple failed"
