Rectifying Typos

diff --git a/testers/utils_virtual b/testers/utils_virtual
--- a/testers/utils_virtual
+++ b/testers/utils_virtual
@@ -647,89 +647,89 @@ function add_server_cluster_SM() {
         #if [[ $DISTRO =~ ubuntu-16.04 ]]; then
         #    sshpass -p "c0ntrail123" scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${TOOLS_WS}/sm_files/preconfig_1604.py root@$SM_SERVER_IP:/opt/contrail/server_manager/client/preconfig.py
         #fi
-        sshpass -p "c0ntrail123" ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -l root $SM_SERVER_IP " (
-            set -e
-            echo "add required image/server/cluster for reimage and provision of the target"
-            cd /root/sm_files 
+        if [ $SKIP_SANITY -e 0 ]
+        then
+            sshpass -p "c0ntrail123" ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -l root $SM_SERVER_IP " (
+                set -e
+                echo "add required image/server/cluster for reimage and provision of the target"
+                cd /root/sm_files 
 
-            set -e
-            echo "add required image/server/cluster for reimage and provision of the target"
+                set -e
+                echo "add required image/server/cluster for reimage and provision of the target"
 
-            echo "delete iso image if it exists"
-            server-manager-client delete image --image_id ${iso_name}
+                echo "delete iso image if it exists"
+                server-manager-client delete image --image_id ${iso_name}
 
-            echo "add base ISO image to server manager database"
-            echo "add base ISO image to server manager database"
-            server-manager-client upload-image --id ${iso_name} --version ${BUILDID} --category image --type ${iso_type} --file_name ${isofile}
-            if [ $? == 0 ]
-            then
-                echo "Server-manager adding image command is successful"
-            else
-                echo "Server-manager adding image command failed, aborting the process"
-                exit 1
-            fi
+                echo "add base ISO image to server manager database"
+                echo "add base ISO image to server manager database"
+                server-manager-client upload-image --id ${iso_name} --version ${BUILDID} --category image --type ${iso_type} --file_name ${isofile}
+                if [ $? == 0 ]
+                then
+                    echo "Server-manager adding image command is successful"
+                else
+                    echo "Server-manager adding image command failed, aborting the process"
+                    exit 1
+                fi
 
-            echo "check if the image was added successfully"
-            server-manager-client display image --json | grep ${iso_name}
-            if [ $? != 0 ]
-            then
-                echo "Adding Base ISO image failed"
-                exit 1
-            fi
+                echo "check if the image was added successfully"
+                server-manager-client display image --json | grep ${iso_name}
+                if [ $? != 0 ]
+                then
+                    echo "Adding Base ISO image failed"
+                    exit 1
+                fi
 
-            echo "delete contrail package if it exists"
-            if [ ${BRANCH} == "R1.10" ]
-            then
-                server-manager delete image $SMID
-            else
-                server-manager delete image --image_id $SMID
-            fi
-            echo "add contrail package to the SM database"
+                echo "delete contrail package if it exists"
+                if [ ${BRANCH} == "R1.10" ]
+                then
+                    server-manager delete image $SMID
+                else
+                    server-manager delete image --image_id $SMID
+                fi
+                echo "add contrail package to the SM database"
 
-            if [[ ( ${BRANCH} > "R3.2.99" ) || ( ${BRANCH} == "mainline" ) ]]
-            then
-                ifconfig eth1 ${SM_CONTROL_IP}
-                server-manager add image -f image.json
-            else
-                echo "Adding contrail package using upload_image command!"
-                server-manager upload_image $SMID ${BUILDID} $pkg_type $contrail_pkg_name
-            fi
-            /root/sm_files/check_image_add.sh $SMID
-            if [ $? == 0 ]
-            then
-                echo "Server-manager adding contrail-package command is successful!!!"
-            else
-                echo "Server-manager adding contrail-package command failed!!! aborting the process"
-                exit 1
-            fi
-    
-            echo "Clean up cluster and server from SM database before adding."
-            server-manager delete server --cluster_id $CLUSTER_NAME
-            server-manager delete cluster --cluster_id $CLUSTER_NAME
-    
-            echo "add cluster to SM database"
-            server-manager add cluster -f $cluster_json
-            if [ $? == 0 ]
-            then
-                echo "Adding cluster to server-manager is sucessful!!!"
-            else
-                echo "Adding cluster to server-manager failed, aborting the process"
-                exit 1
-            fi
-    
-            #${show_cmd} cluster --detail
-    
-            echo "add server to SM database"
-            server-manager add server -f $server_json
-            if [ $? == 0 ]
-            then
-                echo "Adding server to server-manager is sucessful!!!"
-            else
-                echo "Adding server to server-manager failed, aborting the process"
-                exit 1
-            fi
-            if [ $SKIP_SANITY -e 0 ]
-            then
+                if [[ ( ${BRANCH} > "R3.2.99" ) || ( ${BRANCH} == "mainline" ) ]]
+                then
+                    ifconfig eth1 ${SM_CONTROL_IP}
+                    server-manager add image -f image.json
+                else
+                    echo "Adding contrail package using upload_image command!"
+                    server-manager upload_image $SMID ${BUILDID} $pkg_type $contrail_pkg_name
+                fi
+                /root/sm_files/check_image_add.sh $SMID
+                if [ $? == 0 ]
+                then
+                    echo "Server-manager adding contrail-package command is successful!!!"
+                else
+                    echo "Server-manager adding contrail-package command failed!!! aborting the process"
+                    exit 1
+                fi
+        
+                echo "Clean up cluster and server from SM database before adding."
+                server-manager delete server --cluster_id $CLUSTER_NAME
+                server-manager delete cluster --cluster_id $CLUSTER_NAME
+        
+                echo "add cluster to SM database"
+                server-manager add cluster -f $cluster_json
+                if [ $? == 0 ]
+                then
+                    echo "Adding cluster to server-manager is sucessful!!!"
+                else
+                    echo "Adding cluster to server-manager failed, aborting the process"
+                    exit 1
+                fi
+        
+                #${show_cmd} cluster --detail
+        
+                echo "add server to SM database"
+                server-manager add server -f $server_json
+                if [ $? == 0 ]
+                then
+                    echo "Adding server to server-manager is sucessful!!!"
+                else
+                    echo "Adding server to server-manager failed, aborting the process"
+                    exit 1
+                fi
                 echo "Preconfigure the servers"
                 python /opt/contrail/server_manager/client/preconfig.py --server-json $server_json  --server-manager-ip $SM_SERVER_IP --server-manager-repo-port 80    
                 if [ $? == 0 ]
@@ -738,10 +738,11 @@ function add_server_cluster_SM() {
                 else
                     echo "Preconfigure server through server-manager failed, aborting the process"
                     exit 1
-                fi        
-            else
-                echo "Not doing the Preconfig as SKIP_SANITY parameter is not equal to 0 "    
-        ) "
+                fi            
+            ) "
+        else
+            echo "Not adding the images and doing the preconfig as SKIP_SANITY parameter is not set to 0"
+        fi
     fi
 
     if [ $? == 0 ]
@@ -874,7 +875,6 @@ function run_smgr_virtual_task() {
     #Add server and cluster to the SM
     add_server_cluster_SM || debug_and_die "Failed to add server and cluster to SM"
 
-
     if [ $SKIP_SANITY -e 0 ]
     then
         if [[ ( ${BRANCH} > "R2.23" ) || ( ${BRANCH} == "mainline" ) ]]
@@ -907,18 +907,18 @@ function run_smgr_virtual_task() {
             install_dep_pkgs_for_test
             run_sanity || debug_and_die "Run_sanity step failed"
         fi
-
-        run_tempest || die "Run_Tempest step failed"
-        collect_tech_support || die "Task to collect logs/cores failed"
-        #delete_stacks || die "Failed to delete stacks"
-        echo "Ending test on "${AVAILABLE_TESTBEDS}
-        #Set the TBFILE_NAME to the one passed through jenkins job
-        export RUN_SUCCESSFUL=1
-        TBFILE_NAME=${AVAILABLE_TESTBEDS}
-        tb_lock_file=${LOCK_FILE_DIR}/${TBFILE_NAME}
     else
-        echo "Skipping Provisioning and Sanity Run as SKIP_SANITY parameter is not equal to 0 "
+        echo "Not doing the Provisioning and not running sanity as SKIP_SANITY parameter is not set to 0"
     fi
+
+    run_tempest || die "Run_Tempest step failed"
+    collect_tech_support || die "Task to collect logs/cores failed"
+    #delete_stacks || die "Failed to delete stacks"
+    echo "Ending test on "${AVAILABLE_TESTBEDS}
+    #Set the TBFILE_NAME to the one passed through jenkins job
+    export RUN_SUCCESSFUL=1
+    TBFILE_NAME=${AVAILABLE_TESTBEDS}
+    tb_lock_file=${LOCK_FILE_DIR}/${TBFILE_NAME}
 }
 
 
