Continuous build support

diff --git a/testers/utils_virtual b/testers/utils_virtual
--- a/testers/utils_virtual
+++ b/testers/utils_virtual
@@ -122,7 +122,7 @@ function bringup_SM_setup() {
 
     #SM pkg name is different for centos & ubuntu, so set it accordingly.
     #multi-node uses ubuntu SM and single node uses centos SM.
-    if [ $SM_TYPE -eq 1 ] #if multi node refer to ubuntu folder
+    if [ $SM_TYPE -eq 1 ] && [ -z $CONTINUOUS_BUILD ] #if multi node refer to ubuntu folder
     then
         SM_SERVER_PKG_FILE=`ls contrail-server-manager-installer_*\.*-${BUILDID}\~$SKU\_all.deb*`
     else
@@ -133,9 +133,9 @@ function bringup_SM_setup() {
         SM_SERVER_PKG_FILE=`ls contrail-server-manager-installer_*\.*-${BUILDID}\~mitaka\_all.deb*`
     fi
     if [ $CONTINUOUS_BUILD -eq 1 ] ; then
-        pkg_dir = $TOOLS_WS
-        cd $pkg_path
-        sshpass -p "c0ntrail123" scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@10.84.22.50:/var/lib/jenkins/jobs/Continuous-Build-Ubuntu14/builds/${BUILDID}/archive/artifacts/contrail-server-manager-installer_*.deb ${TOOLS_WS}
+        pkg_dir=${TOOLS_WS}
+        cd $pkg_dir
+        sshpass -p "c0ntrail123" scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@10.84.22.50:/var/lib/jenkins/jobs/Continuous-Build-Ubuntu14/builds/lastStableBuild/archive/artifacts/contrail-server-manager-installer_*.deb ${TOOLS_WS}
         SM_SERVER_PKG_FILE=`ls contrail-server-manager-installer_*.deb`
     fi
     pkg_name="$pkg_dir/$SM_SERVER_PKG_FILE"
@@ -625,9 +625,9 @@ function add_server_cluster_SM() {
             contrail_pkg_name=`ls contrail-cloud-docker_*.tgz`
         fi
         if [ $CONTINUOUS_BUILD -eq 1 ]; then
-            pkg_path = $TOOLS_WS 
+            pkg_path=$TOOLS_WS 
             cd $pkg_path
-            sshpass -p "c0ntrail123" scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@10.84.22.50:/var/lib/jenkins/jobs/Continuous-Build-Ubuntu14/builds/${BUILDID}/archive/artifacts/contrail-cloud-docker_*.tgz ${TOOLS_WS} 
+            sshpass -p "c0ntrail123" scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@10.84.22.50:/var/lib/jenkins/jobs/Continuous-Build-Ubuntu14/builds/lastStableBuild/archive/artifacts/contrail-cloud-docker_*.tgz ${TOOLS_WS} 
             contrail_pkg=`ls contrail-cloud-docker_*.tgz`
             contrail_pkg_name=`ls contrail-cloud-docker_*.tgz`
         fi
@@ -885,7 +885,13 @@ function run_smgr_virtual_task() {
         echo "CLUSTER_NAME env is not set, aborting the process"
         exit 1
     fi
-    create_testbed || die "Failed to create required testbed details"
+    
+    if [ -z $CONTINUOUS_BUILD ]; then
+        create_testbed || die "Failed to create required testbed details"
+    else
+        create_testbed_continuous || die "Failed to create required testbed details"
+    fi
+
     bringup_SM_setup || debug_and_die "Failed to bringup SM setup"
     
     #Add server and cluster to the SM
@@ -914,6 +920,14 @@ function run_smgr_virtual_task() {
             export TEST_HOST_USER=`echo $TEST_HOST_STRING | cut -d @ -f1`
             #Copy testbed_file generated by build_infra.sh
             sshpass -p "c0ntrail123" scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@$BASE_CLUSTER:/root/${TEMPLATE_DIR}/testbed.py ${TOOLS_WS}/testbeds/${tb_filename}
+
+            if [ -z $CONTINUOUS_BUILD ]; then
+                setup_testnode || debug_and_die "test node setup failed"
+            else
+                sshpass -p "c0ntrail123" scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@10.84.22.50:/var/lib/jenkins/jobs/Continuous-Build-Ubuntu14/builds/lastStableBuild/archive/artifacts/docker-image-contrail-test*.tar.gz ${TOOLS_WS} 
+                export TEST_CONTAINER_IMAGE_DIR=$TOOLS_WS 
+                setup_testnode || debug_and_die "test node setup failed"
+	    fi
             setup_testnode || debug_and_die "test node setup failed"
             install_dep_pkgs_for_test
             run_sanity_simple || debug_and_die "run_sanity_simple failed"
@@ -972,6 +986,19 @@ function debug_and_die
     cat $tb_lock_file
     python ${TOOLS_WS}/testers/upload.py --pkg_name $PKG_FILE --jenkins_id $SCRIPT_TIMESTAMP
     exit 1
+}
+
+function create_testbed_continuous {
+
+    #search_package || die "Unable to locate package"
+    if [[ $TEST_RUN_INFRA == 'docker' ]]; then
+        # No need to fetch test repos in case of docker
+        checkout_fab_repo || die "Unable to checkout fab/test repos" # No need to checkout test repo for container
+    else
+        checkout_repo
+    fi
+    use_testbed_file || die "Unable to set the testbed properly for use"
+    be_ready_to_reimage_remotely || die "Unable to setup the system for reimaging in US"
 }
 
 function cleanup() {
