Hardcode test-docker version

diff --git a/testers/utils_redhat b/testers/utils_redhat
--- a/testers/utils_redhat
+++ b/testers/utils_redhat
@@ -3,6 +3,62 @@
 TOOLS_WS=${TOOLS_WS:-$(pwd)}
 multi_node=0
 
+function setup_sanity_base_simple {
+    jenkins_triggered=${JENKINS_TRIGGERED:-0}
+
+    # run sanity in parallel/serial branch, default serial
+    if [ "${sanitytype}" = "" ]; then
+        sanitytype="serial"
+    fi
+
+    # OS_TEST_PATH is used for test discovery by testr
+    OTHER_OPTS=""
+    if [ ! -z $OS_TEST_PATH ] ; then
+        OTHER_OPTS="$OTHER_OPTS export CT_OS_TEST_PATH=$OS_TEST_PATH ; "
+    fi
+
+    #PARAMS_FILE=$CFGM_TEST_CODE_PATH/scripts/sanity_params.ini
+    #TEST_CONFIG_FILE=$CFGM_TEST_CODE_PATH/sanity_params.ini
+    if [[ "$TEST_RUN_CMD" == *"control_node_scaling"* ]]; then
+        copy_bgp_stress_test_binary # This is not going to work in container, this will need to happen while building the container
+    fi
+    #Hardcoded test docker version from 4.0.2
+    sanity_cmd="bash -x /usr/local/bin/testrunner.sh run -t ${HOME}/contrail-test-runs/${SCRIPT_TIMESTAMP}/testbed.py ${TEST_RUN}-${TEST_SKU}:4.0.2.0-35"
+    if [ $PARALLEL_RUN -eq 1 ]; then
+         EXTRA_RUN_TEST_ARGS="$EXTRA_RUN_TEST_ARGS -t "
+    fi
+    pythonpath=""
+
+    if [[ "$TEST_RUN_CMD" != *"-d"* ]]; then
+        EXTRA_RUN_TEST_ARGS="$EXTRA_RUN_TEST_ARGS --test-failure-threshold $(failure_threshold_limit) "
+    fi
+    other_test_params=`set_other_test_params`
+
+    exec_cmds -s ${TEST_HOST_STRING} -p ${TEST_HOST_PASSWORD} -c "export CT_SCRIPT_TS=\"${SCRIPT_TIMESTAMP}\";
+                                                         export TEST_RUN_CMD=\"${TEST_RUN_CMD}\";
+                                                         export EXTRA_RUN_TEST_ARGS=\"${EXTRA_RUN_TEST_ARGS}\";
+                                                         export CT_JENKINS_TRIGGERED=${jenkins_triggered};
+                                                         export CT_BUILD_ID=${BUILDID};
+                                                         export CT_PARAMS_FILE=${PARAMS_FILE};
+                                                         export CT_TEST_TYPE=${TEST_TYPE};
+                                                         export CT_EMAIL_SUBJECT_PREFIX=\"${EMAIL_SUBJECT_PREFIX}\";
+                                                         export CT_EMAIL_SUBJECT=\"${EMAIL_SUBJECT}\";
+                                                         export CT_MX_GW_TEST=${MX_GW_TEST};
+                                                         export CT_IMAGE_WEB_SERVER=${IMAGE_WEB_SERVER};
+                                                         export CT_BRANCH=$BRANCH;
+                                                         $OTHER_OPTS
+                                                         $other_test_params
+                                                         $pythonpath
+                                                         ${sanity_cmd};"; rv_test_run=$?
+    if [ $rv_test_run -ne 0 ] && [ $rv_test_run -ne 100 ]; then
+        if [ $rv_test_run -gt 100 ]; then
+            die "Task to run sanity failed"
+        else
+            debug_and_die "Test failures exceed the threshold of $limit percent (Failures: ${rv_test_run}%"
+        fi
+    fi
+}
+
 function setup_testnode {
     if [[ $DISTRO =~ ^(centos|redhat) ]]; then
         PACKAGE_INSTALL_CMD="
@@ -123,8 +179,12 @@ function run_redhat_task() {
         export TEST_HOST_USER=`echo $TEST_HOST_STRING | cut -d @ -f1`
         #Copy testbed_file generated by build_infra.sh
         setup_testnode || debug_and_die "test node setup failed"
-        install_dep_pkgs_for_test
-        run_sanity_simple || debug_and_die "run_sanity_simple failed"
+        #install_dep_pkgs_for_test
+        if [ $SKIP_SANITY -ne 0 ]; then
+            return 0
+        fi
+        search_package
+        setup_sanity_base_simple
     else
         add_sourcelist || die "source.list copy failed on all target nodes"
         install_third_party_pkgs || die "installing GDB/ant failed"
@@ -142,44 +202,6 @@ function run_redhat_task() {
     tb_lock_file=${LOCK_FILE_DIR}/${TBFILE_NAME}
 }
 
-
-function debug_and_die
-{
-    local message=$1
-    #Set the TBFILE_NAME to the one passed through jenkins job
-    TBFILE_NAME=${AVAILABLE_TESTBEDS}
-    tb_lock_file=${LOCK_FILE_DIR}/${TBFILE_NAME}
-    if [ $LOCK_TESTBED_ON_FAILURE -eq 1 ]; then
-        echo "Testbed is set to be locked on failure and add stack info to lock file"
-        #Store stack info in testbed lock file
-        cat ${TOOLS_WS}/info.txt >> ${tb_lock_file} 
-        if [[ $message =~ 'Test failures exceed' ]]; then
-            collect_tech_support
-        fi
-        export RELEASE_TESTBED=0
-        lockfile ${LOCK_FILE_DIR}/lockfile1
-
-        set -x
-        echo "Locking testbed $tb_lock_file for debugging"
-        echo "Testbed locked..Unlock when debug complete" >> $tb_lock_file
-        cat $tb_lock_file
-
-        remove_lock_file
-    else
-        collect_tech_support
-        echo "Testbed stack delete!!!"
-        delete_stacks || die "Failed to delete stacks"
-        if [[ $VCENTER_ONLY_TESTBED -eq 1  || $VCENTER_AS_COMPUTE_TESTBED -eq 1 ]]; then
-            # deregister the setup from vcenter server
-            run_fab cleanup_vcenter
-        fi
-    fi
-    [ -z "$message" ] && message="Died"
-    echo "${BASH_SOURCE[1]}: line ${BASH_LINENO[0]}: ${FUNCNAME[1]}: $message." >&2
-    cat $tb_lock_file
-    python ${TOOLS_WS}/testers/upload.py --pkg_name $PKG_FILE --jenkins_id $SCRIPT_TIMESTAMP
-    exit 1
-}
 
 function cleanup() {
     #Set the TBFILE_NAME to the one passed through jenkins job
